name: CI

on: #存在以下动作时执行脚本
  push:
    branches:
      - master

env: #环境变量
  GIT_USER: AnYing
  GIT_EMAIL: anyingiit@aliyun.com
  THEME_REPO: theme-next/hexo-theme-next
  THEME_BRANCH: master
  THEME_DIR_NAME: hexo-theme-next-master
  DEPLOY_REPO: anyingiit/anyingiit.github.io
  DEPLOY_BRANCH: master

jobs: #工作流
  build: #编译
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps: #执行的步骤
      - name: Checkout #调用 actions/checkout@v2 可以实现 Checkout 一个 git 仓库到容器。with.repo 不填写默认为Checkout当前仓库。
        uses: actions/checkout@v2

      - name: Checkout theme repo # Checkout 主题
        uses: actions/checkout@v2
        with: #将repository的ref分支, Checkout到path
          repository: ${{ env.THEME_REPO }} # git地址
          ref: ${{ env.THEME_BRANCH }} # git分支
          path: themes/${{ env.THEME_DIR_NAME }} # 目标路径
          
      - name: Checkout theme-next-pace # Checkout theme-next-pace
        uses: actions/checkout@v2
        with: 
          repository: theme-next/theme-next-pace
          ref: master
          path: themes/${{ env.THEME_DIR_NAME }}/source/lib/pace

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with: # 将gitgage页面cheout到path
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }} #构建制定node环境
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
          THEME_DIR_NAME: ${{ env.THEME_DIR_NAME }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.theme.yml themes/$THEME_DIR_NAME/_config.yml
      
      - name: Install dependencies
        run: |
          yarn install
      
      - name: Install Hexo
        run: |
          npm install -g hexo

      - name: Generate hexo
        run: |
          hexo generate

      - name: Deploy hexo
        run: |
          hexo deploy
